
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmSoporte extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSoporte
     */
    public jfrmSoporte() {
        initComponents();
        this.setTitle("Motherboard");
        this.setLocationRelativeTo(null);
        this.setSize(900,500);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblNomPieza = new javax.swing.JLabel();
        jlblPiezas = new javax.swing.JLabel();
        jlblConcepto = new javax.swing.JLabel();
        jlblFuncion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jlblNomPieza.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlblNomPieza.setForeground(new java.awt.Color(0, 0, 102));
        jlblNomPieza.setText(".");

        jlblPiezas.setForeground(new java.awt.Color(0, 0, 102));

        jlblConcepto.setText(".");

        jlblFuncion.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jlblNomPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jlblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlblNomPieza)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblPiezas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        jMenuItem4.setText("Placa Base");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Memoria RAM");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de Poder");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem11.setText("Bateria CMOS");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("BIOS/UEFI");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Cable de Alimentacion");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Cable SATA");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Disco Duro SSD");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Tarjeta de Red");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Tarjeta de Sonido");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Tarjeta de Video");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Ventilador de Gabinete");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("Disco Duro HDD");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem9.setText("Acerca del Programa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Creditos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Motherboard");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Es la tarjeta de circuito impreso principal de la computadora. Funciona como la \"columna vertebral\" del sistema. ");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Interconectar y comunicar todos los demás componentes para que trabajen juntos");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png"))); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         jlblNomPieza.setText("");
        jlblNomPieza.setText("Procesador");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Es el cerebro de la computadora. Un chip de silicio encargado de realizar operaciones lógicas y matemáticas.");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Interpretar y ejecutar las instrucciones de los programas y del sistema operativo, procesando todos los datos necesarios.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cpu.png"))); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int msg=JOptionPane.showConfirmDialog(null, "Desea Salir del Software 😁");
    if (msg==0)
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Memoria Ram");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Memoria de acceso aleatorio de alta velocidad y carácter volátil");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion Almacenar temporalmente los datos de los programas y archivos que estás usando en el momento");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ram.png"))); 
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Este programa nos ayuda a reconocer y aprender sobre cada parte de una computadora de forma visual de manera sencilla");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hecho por: Erick Sebastian Ramirez Arana IVD 24");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Cooler");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Un sistema de enfriamiento que va montado directamente sobre el procesador.");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Absorber y disipar el calor extremo que genera el CPU para evitar que se sobrecaliente ");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cooler.png"))); 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Fuente de poder");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: El componente que se encarga de transformar la corriente eléctrica de la pared en una forma que la PC pueda usar");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Suministrar energía eléctrica limpia, estable y con el voltaje adecuado a todos los componentes de la computadora.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuente.png"))); 
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Bios/UEFI");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: : El firmware o software básico preinstalado en un chip de la motherboard. La UEFI es la versión moderna y visual de la clásica BIOS. ");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Es lo primero que se ejecuta al encender la PC. Su trabajo es hacer un testeo rápido del hardware conectado (POST), gestionar los parámetros de energía y arranque,"
                + " y darle el control al sistema operativo para que inicie");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/biosuefi.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:jlblNomPieza.setText("");
        jlblNomPieza.setText("Bateria CMOS");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Una pequeña pila de botón (generalmente una CR2032) ubicada en la motherboard. ");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Mantener energizado el chip de la BIOS/UEFI cuando la computadora está completamente apagada y desconectada,"
                + " evitando que se borren la hora, la fecha y las configuraciones del sistema.");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Bateria.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Cable de Alimentacion");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Puede referirse al cable externo (que va del enchufe a la Fuente de Poder) o a los cables internos de la fuente. ");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: ransportar la energía eléctrica desde la toma de corriente hacia la fuente de poder, o desde la fuente hacia componentes específicos ");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/CableAlimentacion.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Cable Sata");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Un cable de datos plano de 7 pines. ");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Conectar discos duros (HDD), unidades de estado sólido (SSD de 2.5 pulgadas) y lectoras de discos a la motherboard para la transferencia de datos. ");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/CableSata.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Disco Duro SSD");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Unidad de estado sólido que almacena datos en chips de memoria flash");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: es muchísimo más rápido, lo que acelera el encendido de la PC y la carga de juegos que el HDD");
     javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/DiscoSata.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal); 
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Tarjeta de Red");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Un chip o tarjeta de expansión Ethernet o Wi-Fi encargado de la conectividad.");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Permitir que la computadora se conecte a una red local o a Internet,"
                + " ya sea mediante un cable de red o de forma inalámbrica. ");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/TarjetaRed.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Tarjeta de Sonido");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto:Un dispositivo de hardware dedicado al audio.");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: : Convertir las señales digitales de la PC en analógicas para que las escuches en tus bocinas/audífonos,"
                + " y viceversa para grabar audio con un micrófono. ");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/TarjetaSonido.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Tarjeta de Video");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Un procesador especializado y diseñado para el procesamiento visual.");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Procesar los datos relacionados con imágenes, videos, entornos 3D y juegos, y traducirlos en una señal que tu monitor pueda mostrar. ");
       javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/TarjetaVideo.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Ventilador de Gabinete");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Ventiladores estratégicamente distribuidos en la caja o chasis de la computadora. ");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Crear un flujo de aire constante. Meten aire frío del exterior y expulsan el aire caliente acumulado dentro del gabinete ");
        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Ventilador.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("Disco Duro HDD");
        jlblConcepto.setText("");
        jlblConcepto.setText("Concepto: Dispositivo de almacenamiento magnético tradicional compuesto por discos mecánicos");
        jlblFuncion.setText("");
        jlblFuncion.setText("Funcion: Guardar de forma permanente el sistema operativo, programas y archivos personales.");
       javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Disco.png"));
java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
javax.swing.ImageIcon iconoFinal = new javax.swing.ImageIcon(imagenEscalada);
jlblPiezas.setIcon(iconoFinal);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSoporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblConcepto;
    private javax.swing.JLabel jlblFuncion;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPiezas;
    // End of variables declaration//GEN-END:variables
}
